title: Jordan Schilling's Developer Portfolio
author: Jordan Schilling
logo: /assets/img/logo.png
description: The inner thinking of a software developer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: "https://jordanschilling.me"
baseurl: ""
